### ISSUE TITLE
Standardize JVM option settings

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#116]
As a developer, I'd like to standardize JVM option settings, to it is consistently applied in all the deployer implementations.

**Comment by dsyer** [comment]
After some back channel chat it seems that for the local deployer we need `JAVA_OPTS` to be `spring.cloud.deployer.javaOpts` (and/or `*.java-opts` via relaxed binding) in `AbstractLocalDeployerSupport`. Then dataflow apps can accept deployment options `app.<name>.spring.cloud.deployer.javaOpts` and the global defaults can be set as `spring.cloud.dataflow.applicationProperties.stream.spring.cloud.deployer.javaOpts` in the dataflow local server app.

**Comment by markpollack** [comment]
Not sure how we can generally javaOpts at the deployer level since for example,  wrt to JVM memory in PCF you can't set the ones you are probably settings now related to memory.

https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-java_opts.md#memory-settings.

There is another story for bringing spring.cloud.deployer.memory and disk to the top level

https://github.com/spring-cloud/spring-cloud-dataflow/issues/658

which might be more portable, but have different meanings on different impls, e.g. it could refer to max JVM memory in the local deployer case (via java-opts) but overall container memory for other platforms.

**Comment by markfisher** [comment]
+1 for having `spring.cloud.deployer.memory` map to `-X` args in the local deployer case (as opposed to relying on `javaOpts`, even for local)

**Comment by markpollack** [comment]
For the app-starters the docker file we create is not taking JAVA_OPTS into account, we should improve the dockerfile to have `ENTRYPOINT exec java $JAVA_OPTS -jar /myapp.jar`

**Comment by spencergibb** [comment]
The original `JAVA_OPTS` PR was for java system properties so STS could communicate with spring cloud cli deployed apps.

**Comment by dsyer** [comment]
It has't made it into a release yet though, has it, so can we change it to `javaOpts` at least for 1.0.x?
