### ISSUE TITLE
Manage .m2 cache size

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#131]
As a developer, I'd like to come up with a design to cleanup local maven cache, so it doesn't accumulate to remain unmanaged.

**Comment by markpollack** [comment]
Changing the aether code, while doable, is more difficult than just adding some code into the one entry point we have into that library to perform some manual (java.io.File style) clean up.  This blog post show some of the code that we will likely need to add in order to apply some strategies for cleanup (delete oldest first etc)

http://blog.trifork.com/2011/08/01/cleaning-up-your-maven-repository/

**Comment by ericbottard** [comment]
The real problem IMHO is that we don't control the scope of the resolved MavenResource.
When is it safe to delete files?

**Comment by markpollack** [comment]
This issue probably belongs in the CF deployer project.

There is only one entry point into the aether library to download the artifact to the local disk.  That is happening inside `CloudFoundryAppDeployer.pushApplication` - the call to `getApplication` will call `request.getResource().getFile().toPath();` and that is what does the resolution/download.  

https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java#L284

If we surround this method with an appropriate lock based on a fully qualified name of the resource, then right after the app is pushed to CF, we can do cleanup of that specific artifact.  For example, we can look to remove all older versions of the app that was just deployed and maybe fallback to deleting the app itself is disk space is still low.

**Comment by gregturn** [comment]
It may be tricky to keep inside the scope of the SPI, since `deploy` and `status` are separate operations.

I'd argue that the user should invoke the cleanup after `status` shows the proper results.

As an example, this is how I'm using the CF Deployer. I definitely plan to add a cleanup step after the highlighted line (wrapped in a poller).

https://github.com/gregturn/clouddriver/blob/reactor/clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/deploy/handlers/CloudFoundryDeployHandler2.groovy#L158

**Comment by markpollack** [comment]
I don't understand how `status` enters into this discussion of disk mgmt.  I'm hoping that keeping just the latest version of each .jar file around will be efficient enough on the disk usage.  If a deployed app succeeds or fails that does not seem to be a concern to how we manage the disk usage.

**Comment by markpollack** [comment]
Note I did not consider the tab-completion/metadata use case but I think the cleanup on the deploy step would manage to cleanup .jars that got pulled in from doing tab completion.

**Comment by ericbottard** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/233
