### ISSUE TITLE
Switch to maven's aether provider

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#132]
As a developer, I'd like to switch to Maven's [Aether extension APIs](http://maven.apache.org/ref/3.3.9/maven-aether-provider/) instead of the standalone Aether library, so we don't have to depend on external library for artifact resolution.

**Comment by ericbottard** [comment]
I don't understand the rationale behind this.
Moreover, the linked project (assuming it is embeddable) was [last released in 2015](https://mvnrepository.com/artifact/org.apache.maven/maven-aether-provider), earlier than what we currently use, no?

**Comment by markpollack** [comment]
When looking at the Aether project I noticed that classes hadn't been touched for much longer, for example [VersionRangeResolver](https://github.com/eclipse/aether-core/blob/master/aether-impl/src/main/java/org/eclipse/aether/impl/VersionRangeResolver.java) is from May 2014 and generally speaking the project has not had a commit in a very long time (Nov 25, 2014).  I thought that the 'impl' package implied some implementation and we may have been picking up older unmaintained code.

It turns out there isn't an implementation of the VersionRangeResolver in that package, nor of other interfaces.  Maven is providing the implementations and we are picking them up via the utility method `MavenRepositorySystemUtils.newServiceLocator()`.   

So we don't need to change anything to pick up the latest maintained implementations of the Aether interfaces.

Strange that Aether itself didn't provide the implementation, but whatever.  Closing this issue.
