### ISSUE TITLE
Add a configurable option to turn-on "development mode"

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#193]
As a user, I'd like to have the ability to turn off [caching](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/support/DelegatingResourceLoader.java#L119-L136) of the application artifacts, so I don't have to worry about disk quota limits while experimenting in the development phase. 

**Acceptance:**
- Caching enabled by default and it can be turned off through a configuration property
- Documentation include the pros/cons of disabling the caching (_eg., performance; disk-quota limits_)

**Comment by ericbottard** [comment]
Nope.

We're always gonna put the file on disk (we need to). The problem comes from the fact that the same remote location is always cached to the same disk location (ie assumes resources do not change at the other end).

At the very best, we could allow disabling this behavior, which would **on the contrary** put a lot more pressure on disk space.

**Comment by sabbyanandan** [comment]
Closing this in favor of spring-cloud/spring-cloud-deployer#235.
