### ISSUE TITLE
Support getFile() for all resources

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-deployer#39]
`Resource.getFile()` doesn't work for all resource types as for example with `UrlResource` which points to `http` you're expected to use inputstream. The one using `Resource` would not know and anyway requirement is to get access to actual physical file so I think we should transparently support a caching so that `getFile()` works.

This requirement is coming from https://github.com/spring-cloud/spring-cloud-deployer/issues/38. While user could first try to use File, then fallback to inputstream and create a tmp file, it's best to handle this transparently in a deployer core classes where we keep `Resource` support classes. We just need to make a cache directory, possibly outside of system tmp dir, so that in a perfect world file(s) are only downloaded once.

**Comment by jvalkeal** [comment]
Right, maybe unnecessary ticket as I thought #38 which I linked was in `spring-cloud-dataflow`. Too many waffles :)

**Comment by markfisher** [comment]
Seems like we might just want to expand (and rename) `DelegatingResourceLoader` so that it can first try `getFile()` and then if that fails, try `getInputStream()` to read the content and write to a "local" storage (in quotes because that storage could actually be some type of blob store if running on a platform where there is no local persistent volume as mentioned by @sabbyanandan on the other related issue).

**Comment by ericbottard** [comment]
Boot magical ClassLoader needs a `java.io.File`

**Comment by jvalkeal** [comment]
Yes, as Eric mentioned, we need a physical file cache directory. Deployer could probably get away from it by not using local cache, but controller working with shell needs that `File` handle.

**Comment by markfisher** [comment]
Right, but it really is just a cache, so a temp file is sufficient.
