### ISSUE TITLE
List maven repositories that were used when resolution of artifact fails

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer#89]
the error message

```
dataflow:>stream create --name http2file --definition "http | mytransformer | log" --deploy
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource: org.springframework.cloud.stream.app:log-sink-rabbit:jar:1.0.0.BUILD-SNAPSHOT

failed to resolve MavenResource: org.springframework.cloud.stream.app:log-sink-rabbit:jar:1.0.0.BUILD-SNAPSHOT

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource: org.springframework.cloud.stream.app:log-sink-rabbit:jar:1.0.0.BUILD-SNAPSHOT
```

should have more info on remote repo locations.

**Comment by markfisher** [comment]
Do you have the full trace? As far as I know the repository URL is listed in the trace, but not exactly where you would expect.

**Comment by ghillert** [comment]
Some discussion points:

The PR is at best a work-around. Ideally the deployer's resource resolution should have proper (abstracted) exception handling defined. 

At present the Deployer SPI does not define exception handling well. We use the super generic `org.springframework.core.io.Resource` class backed by the generic `ResourceLoader` so that everything is abstracted away. Unfortunately, those classes don't define exception handling.
